modLoader="javafml"
loaderVersion="[42,)"
license="All rights reserved"
[[mods]]
modId="l2magic"
version="${file.jarVersion}" #mandatory
displayName="L2 Archery" #mandatory
logoFile="l2magic.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2magic]]
    modId="forge"
    mandatory=true
    versionRange="[42.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2magic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2magic]]
    modId="l2library"
    mandatory=true
    versionRange="[1.7.0,)"
    ordering="AFTER"
    side="BOTH"