modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="l2magic"
version="${file.jarVersion}" #mandatory
displayName="L2 Magic" #mandatory
logoFile="l2magic.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2magic]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.l2magic]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
[[dependencies.l2magic]]
modId="l2library"
mandatory=true
versionRange="[2.4.25,)"
ordering="AFTER"
side="BOTH"
[[dependencies.l2magic]]
modId="l2complements"
mandatory=true
versionRange="[2.4.36,)"
ordering="AFTER"
side="BOTH"
